# Name of the domain bridge, used for node naming and logging
name: onboard_bridge
# 地面站域ID
from_domain: 0
# 无人机域ID
to_domain: 1
topics:
  # Bridge "/onboard/cmd" topic from 地面站 to 无人机
  /onboard/cmd:
    type: onboard_msgs/msg/OnboardCommand
  # Bridge reversed "/onboard/state" topic
  /onboard/state:
    type: onboard_msgs/msg/OnboardState
    # Reverse 'from' and 'to' domains (bridge from 无人机 to 地面站)
    reversed: True