# Name of the domain bridge, used for node naming and logging
name: onboard_bridge
# 无人机域ID
from_domain: 1
# 地面站域ID
to_domain: 0
topics:
  # 无人机到地面站
  /onboard/state:
    type: onboard_msgs/msg/OnboardState
  # 地面站到无人机
  /onboard/cmd:
    type: onboard_msgs/msg/OnboardCommand
    reversed: True