# Name of the domain bridge, used for node naming and logging
name: onboard_bridge
# 无人机域ID
from_domain: 1
# 地面站域ID
to_domain: 0
topics:
  # 无人机到地面站
  /onboard/state:
    type: onboard_msgs/msg/OnboardState
  # 地面站到无人机
  /onboard/cmd:
    type: onboard_msgs/msg/OnboardCommand
    reversed: True
  # 靶标无人机GPS坐标到跟踪无人机
  /uav6/global_position/global:
    type: sensor_msgs/msg/NavSatFix
    from_domain: 6
    to_domain: 4
  # 靶标无人机姿态到跟踪无人机
  /uav6/local_position/pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 6
    to_domain: 4